Assignment - 1 (AI ML)

Name    : Sushil Krishnan

Reg. No.: 21BCE3009

Mail    : sushil.krishnan2021@vitstudent.ac.in

**SET 1**

In [19]:
import pandas as pd
import numpy as np

Task - 1 Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [20]:
df = pd.DataFrame(np.random.randint(0,10000,size=(4, 4)))
df

      0     1     2     3
0  6779  3818  2382  6120
1  2947  7152  4080  3237
2  6584   388   880  7853
3  5089  3835  5493  4700

Task - 2 Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [21]:
df.columns = ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0            6779            3818            2382            6120
1            2947            7152            4080            3237
2            6584             388             880            7853
3            5089            3835            5493            4700

Task - 3 Find the descriptive statistics of the 'df' dataframe.

In [22]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean      5349.750000     3798.250000     3208.750000     5477.500000
std       1770.812125     2761.592822     2006.943509     1973.166068
min       2947.000000      388.000000      880.000000     3237.000000
25%       4553.500000     2960.500000     2006.500000     4334.250000
50%       5836.500000     3826.500000     3231.000000     5410.000000
75%       6632.750000     4664.250000     4433.250000     6553.250000
max       6779.000000     7152.000000     5493.000000     7853.000000


Task - 4 Check for the null values in 'df' and find the data type of the columns.

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random value 1  4 non-null      int64
 1   Random value 2  4 non-null      int64
 2   Random value 3  4 non-null      int64
 3   Random value 4  4 non-null      int64
dtypes: int64(4)
memory usage: 256.0 bytes

Task - 5 Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

In [24]:
df.loc[:,'Random value 2':'Random value 3']

   Random value 2  Random value 3
0            3818            2382
1            7152            4080
2             388             880
3            3835            5493

In [25]:
df.iloc[:,1:3]

   Random value 2  Random value 3
0            3818            2382
1            7152            4080
2             388             880
3            3835            5493



---

**SET 2**

Task - 1 Create a pandas dataframe (DataFrame name as 'df') (10 observation and 5 features)

In [26]:
dff = pd.DataFrame(np.random.randint(0,10000,size=(10, 5)))
dff

      0     1     2     3     4
0  5205  3104  3655  4676   664
1  7724  2162  7236  6363  4692
2  3937  3663  7269  7509  4455
3  6080   158   267  4207  7843
4  6360  4671  5954  6149  4234
5  7069  4399  2106  1432  5275
6  3784  2642   327  3235  1540
7  9953  9079  4007  2093  7966
8  7121  9124  7844  4248  6087
9   552  1207  7054  2313  1775


Task - 2 Check the info of 'df'

In [27]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10 non-null     int64
 1   1       10 non-null     int64
 2   2       10 non-null     int64
 3   3       10 non-null     int64
 4   4       10 non-null     int64
dtypes: int64(5)
memory usage: 528.0 bytes


Task 3 - Check the descriptive statistics of 'df'

In [28]:
dff.describe()

                 0            1            2            3            4
count    10.000000    10.000000    10.000000    10.000000    10.000000
mean   5778.500000  4020.900000  4571.900000  4222.500000  4453.100000
std    2584.623731  3006.609329  2923.872183  2006.760366  2523.176325
min     552.000000   158.000000   267.000000  1432.000000   664.000000
25%    4254.000000  2282.000000  2493.250000  2543.500000  2389.750000
50%    6220.000000  3383.500000  4980.500000  4227.500000  4573.500000
75%    7108.000000  4603.000000  7190.500000  5780.750000  5884.000000
max    9953.000000  9124.000000  7844.000000  7509.000000  7966.000000


Task 4 - check the 4th index observation with 'loc' slicing operator.

In [29]:
dff.loc[4]

0    6360
1    4671
2    5954
3    6149
4    4234
Name: 4, dtype: int64


Task 5 - Check the null values in your 'df'

In [32]:
dff.isnull().any()

0    False
1    False
2    False
3    False
4    False
dtype: bool